name: Go Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5" # Specify the Go version you are using

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      # - name: Run tests with coverage
      #   run: go test -coverprofile=coverage.out ./...

      # - name: Upload coverage report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-report
      #     path: coverage.out
